/* Header file for function SpaceSegment
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void spacesegment_startup(void);

/* Provided interfaces */
void spacesegment_PI_tc( const asn1SccTestInteger * );

/* Required interfaces */
extern void spacesegment_RI_tm( const asn1SccTestInteger * );


#ifdef __cplusplus
}
#endif
