/* Body file for function SpaceSegment
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "spacesegment.h"


void spacesegment_startup(void)
{

}

void spacesegment_PI_tc
      (const asn1SccTestInteger *IN_request)

{
    const asn1SccTestInteger data = (*IN_request + 1) % 1000;
    spacesegment_RI_tm(&data);
}


