/* Body file for function corecomponent
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "corecomponent_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void corecomponent_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

extern void init_utilitycomponent(void);
extern unsigned utilitycomponent_initialized;
unsigned corecomponent_initialized = 0;
void init_corecomponent(void)
{
   if (0 == corecomponent_initialized) {
      corecomponent_initialized = 1;
      // Call user code startup function
      extern void corecomponent_startup(void);
      corecomponent_startup();
      corecomponent_initialized = 2;
   }
}
void corecomponent_tc
      (const char *IN_request, size_t IN_request_len)

{
   sender_pid = corecomponent_tc_get_sender();
   
   static asn1SccTestInteger IN_REQUEST;
   int request_error_code = 0;

   if (0 != Decode_ACN_TestInteger (&IN_REQUEST, (void *)IN_request, IN_request_len, &request_error_code)) {
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void corecomponent_PI_tc
      (const asn1SccTestInteger *);





   // Call user code
   corecomponent_PI_tc (&IN_REQUEST);

}

