/* Header file for function corecomponent
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void corecomponent_startup(void);

/* Provided interfaces */
void corecomponent_PI_tc( const asn1SccTestInteger * );

/* Required interfaces */
extern void corecomponent_RI_computep( const asn1SccTestInteger *, const asn1SccTestInteger *, asn1SccTestInteger * );


extern void corecomponent_RI_computeup( const asn1SccTestInteger *, const asn1SccTestInteger *, asn1SccTestInteger * );


extern void corecomponent_RI_tm( const asn1SccTestStruct * );


#ifdef __cplusplus
}
#endif
