/* Body file for function corecomponent
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "corecomponent.h"
//#include <stdio.h>


void corecomponent_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[corecomponent] Startup");
}

void corecomponent_PI_tc
      (const asn1SccTestInteger *IN_request)

{
   // Write your code here
}


