/* Body file for function SpaceSegment
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "spacesegment_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void spacesegment_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned spacesegment_initialized = 0;
void init_spacesegment(void)
{
   if (0 == spacesegment_initialized) {
      spacesegment_initialized = 1;
      // Call user code startup function
      extern void spacesegment_startup(void);
      spacesegment_startup();
      spacesegment_initialized = 2;
   }
}
void spacesegment_tc
      (const char *IN_request, size_t IN_request_len)

{
   sender_pid = spacesegment_tc_get_sender();
   
   static asn1SccTestInteger IN_REQUEST;
   int request_error_code = 0;

   if (0 != Decode_ACN_TestInteger (&IN_REQUEST, (void *)IN_request, IN_request_len, &request_error_code)) {
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void spacesegment_PI_tc
      (const asn1SccTestInteger *);





   // Call user code
   spacesegment_PI_tc (&IN_REQUEST);

}

