/* Body file for function Function1
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "function1_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void function1_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned function1_initialized = 0;
void init_function1(void)
{
   if (0 == function1_initialized) {
      function1_initialized = 1;
      // Call user code startup function
      extern void function1_startup(void);
      function1_startup();
      function1_initialized = 2;
   }
}
void function1_trigger(void)
{
   sender_pid = function1_trigger_get_sender();

   //  Directly call user code, no parameters to pass
   extern void function1_PI_trigger(void);
   function1_PI_trigger();
   // puts ("function1_trigger called");
}

