/* Body file for function Function1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function1.h"
#ifdef unix
#include <stdio.h>
#endif

void function1_startup(void)
{

}

void function1_PI_trigger(void)
{
#ifdef unix
    printf("Tick");
#endif
}


