/* Body file for function utilitycomponent
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "utilitycomponent_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void utilitycomponent_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned utilitycomponent_initialized = 0;
void init_utilitycomponent(void)
{
   if (0 == utilitycomponent_initialized) {
      utilitycomponent_initialized = 1;
      // Call user code startup function
      extern void utilitycomponent_startup(void);
      utilitycomponent_startup();
      utilitycomponent_initialized = 2;
   }
}
void utilitycomponent_computep
      (const char *IN_a, size_t IN_a_len,
       const char *IN_b, size_t IN_b_len,
       char *OUT_c, size_t *OUT_c_len)

{
   sender_pid = utilitycomponent_computep_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void utilitycomponent_PI_computep
      (const asn1SccTestInteger *,
       const asn1SccTestInteger *,
       asn1SccTestInteger *);





   // Call user code
   utilitycomponent_PI_computep ((asn1SccTestInteger *)IN_a, (asn1SccTestInteger *)IN_b, (asn1SccTestInteger *)OUT_c);

}




void utilitycomponent_computeup
      (const char *IN_a, size_t IN_a_len,
       const char *IN_b, size_t IN_b_len,
       char *OUT_c, size_t *OUT_c_len)

{
   sender_pid = utilitycomponent_computeup_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void utilitycomponent_PI_computeup
      (const asn1SccTestInteger *,
       const asn1SccTestInteger *,
       asn1SccTestInteger *);





   // Call user code
   utilitycomponent_PI_computeup ((asn1SccTestInteger *)IN_a, (asn1SccTestInteger *)IN_b, (asn1SccTestInteger *)OUT_c);

}

