/* Header file for function utilitycomponent
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#include "utilitycomponent.h"

// Function initialization - calls user startup code of all dependent functions
void init_utilitycomponent(void);


/* Provided interfaces */
void utilitycomponent_computep
      (const char *IN_a, size_t IN_a_len,
       const char *IN_b, size_t IN_b_len,
       char *OUT_c, size_t *OUT_c_len);



void utilitycomponent_computeup
      (const char *IN_a, size_t IN_a_len,
       const char *IN_b, size_t IN_b_len,
       char *OUT_c, size_t *OUT_c_len);


#ifdef __cplusplus
}
#endif

