/* Body file for function orchestratorcomponent
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "orchestratorcomponent.h"

extern void ardu_print(char* data);
extern void int_to_string(asn1SccTestInteger value, char* buffer);

void orchestratorcomponent_startup(void)
{

}

void orchestratorcomponent_PI_tm
      (const asn1SccTestStruct *IN_response)

{
   char buffer[16];
   ardu_print("TM received ");
   int_to_string(IN_response->id, buffer);
   ardu_print(buffer);
   ardu_print("\n");
   for (int i = 0; i < IN_response->payload.nCount; i++)
   {
      int_to_string(IN_response->payload.arr[i], buffer);
      ardu_print(buffer);
      ardu_print("\n");
   }
}


void orchestratorcomponent_PI_trigger(void)
{
   static asn1SccTestInteger i = 0;
   char buffer[16];
   i++; 
   ardu_print("Trigger ");
   int_to_string(i, buffer);
   ardu_print(buffer);
   ardu_print("\n");
   
   orchestratorcomponent_RI_tc(&i);
}


