/* Header file for function orchestratorcomponent
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void orchestratorcomponent_startup(void);

/* Provided interfaces */
void orchestratorcomponent_PI_tm( const asn1SccTestStruct * );


void orchestratorcomponent_PI_trigger( void );

/* Required interfaces */
extern void orchestratorcomponent_RI_tc( const asn1SccTestInteger * );


#ifdef __cplusplus
}
#endif
