/* Body file for function orchestratorcomponent
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "orchestratorcomponent.h"
//#include <stdio.h>


void orchestratorcomponent_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[orchestratorcomponent] Startup");
}

void orchestratorcomponent_PI_tm
      (const asn1SccTestStruct *IN_response)

{
   // Write your code here
}


void orchestratorcomponent_PI_trigger(void)
{
   // Write your code here
}


