/* Body file for function orchestratorcomponent
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "orchestratorcomponent_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void orchestratorcomponent_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned orchestratorcomponent_initialized = 0;
void init_orchestratorcomponent(void)
{
   if (0 == orchestratorcomponent_initialized) {
      orchestratorcomponent_initialized = 1;
      // Call user code startup function
      extern void orchestratorcomponent_startup(void);
      orchestratorcomponent_startup();
      orchestratorcomponent_initialized = 2;
   }
}
void orchestratorcomponent_tm
      (const char *IN_response, size_t IN_response_len)

{
   sender_pid = orchestratorcomponent_tm_get_sender();
   
   static asn1SccTestStruct IN_RESPONSE;
   int response_error_code = 0;

   if (0 != Decode_ACN_TestStruct (&IN_RESPONSE, (void *)IN_response, IN_response_len, &response_error_code)) {
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void orchestratorcomponent_PI_tm
      (const asn1SccTestStruct *);





   // Call user code
   orchestratorcomponent_PI_tm (&IN_RESPONSE);

}




void orchestratorcomponent_trigger(void)
{
   sender_pid = orchestratorcomponent_trigger_get_sender();

   //  Directly call user code, no parameters to pass
   extern void orchestratorcomponent_PI_trigger(void);
   orchestratorcomponent_PI_trigger();
   // puts ("orchestratorcomponent_trigger called");
}

