/* ASN.1 System configuration file for function orchestratorcomponent
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_TestStruct_ACN
#define __NEED_TestInteger_ACN
