/* Header file for function utilitycomponent
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void utilitycomponent_startup(void);

/* Provided interfaces */
void utilitycomponent_PI_computep( const asn1SccTestInteger *, const asn1SccTestInteger *, asn1SccTestInteger * );


void utilitycomponent_PI_computeup( const asn1SccTestInteger *, const asn1SccTestInteger *, asn1SccTestInteger * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
