/* Body file for function utilitycomponent
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "utilitycomponent.h"
//#include <stdio.h>


void utilitycomponent_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[utilitycomponent] Startup");
}

void utilitycomponent_PI_computep
      (const asn1SccTestInteger *IN_a,
       const asn1SccTestInteger *IN_b,
       asn1SccTestInteger *OUT_c)

{
   // Write your code here
}


void utilitycomponent_PI_computeup
      (const asn1SccTestInteger *IN_a,
       const asn1SccTestInteger *IN_b,
       asn1SccTestInteger *OUT_c)

{
   // Write your code here
}


